# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/raul/OS/Users/king_/Desktop/carrera/curso2018-2019/2oCuatri/TFG/gui_dbjudge/sql_judge/view/qt_view/exam/exam_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Exam(object):
    def setupUi(self, Exam):
        Exam.setObjectName("Exam")
        Exam.resize(634, 480)
        self.gridLayout_2 = QtWidgets.QGridLayout(Exam)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.database_output = QtWidgets.QTextBrowser(Exam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.database_output.sizePolicy().hasHeightForWidth())
        self.database_output.setSizePolicy(sizePolicy)
        self.database_output.setObjectName("database_output")
        self.gridLayout.addWidget(self.database_output, 1, 2, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 7, 1, 1)
        self.question_list = QtWidgets.QListView(Exam)
        self.question_list.setObjectName("question_list")
        self.gridLayout.addWidget(self.question_list, 1, 0, 3, 1)
        self.question = QtWidgets.QLabel(Exam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question.sizePolicy().hasHeightForWidth())
        self.question.setSizePolicy(sizePolicy)
        self.question.setText("")
        self.question.setObjectName("question")
        self.gridLayout.addWidget(self.question, 0, 3, 1, 4)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Exam)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 3, 2, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(Exam)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 2, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 7, 1, 1)
        self.exit_button = QtWidgets.QPushButton(Exam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_button.sizePolicy().hasHeightForWidth())
        self.exit_button.setSizePolicy(sizePolicy)
        self.exit_button.setObjectName("exit_button")
        self.gridLayout.addWidget(self.exit_button, 5, 2, 1, 1)
        self.generate_report_button = QtWidgets.QPushButton(Exam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_report_button.sizePolicy().hasHeightForWidth())
        self.generate_report_button.setSizePolicy(sizePolicy)
        self.generate_report_button.setObjectName("generate_report_button")
        self.gridLayout.addWidget(self.generate_report_button, 5, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Exam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 4, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.test_button = QtWidgets.QPushButton(Exam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_button.sizePolicy().hasHeightForWidth())
        self.test_button.setSizePolicy(sizePolicy)
        self.test_button.setObjectName("test_button")
        self.horizontalLayout.addWidget(self.test_button)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 4, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Exam)
        QtCore.QMetaObject.connectSlotsByName(Exam)

    def retranslateUi(self, Exam):
        _translate = QtCore.QCoreApplication.translate
        Exam.setWindowTitle(_translate("Exam", "Exam"))
        self.label.setText(_translate("Exam", "<html><head/><body><p><span style=\" font-size:18pt;\">Introduce la consulta:</span></p></body></html>"))
        self.exit_button.setText(_translate("Exam", "Salir"))
        self.generate_report_button.setText(_translate("Exam", "Terminar y corregir preguntas"))
        self.label_2.setText(_translate("Exam", "<html><head/><body><p><span style=\" font-size:16pt;\">Pregunta:</span></p></body></html>"))
        self.test_button.setText(_translate("Exam", "Probar consulta"))
