# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/raul/OS/Users/king_/Desktop/carrera/curso2018-2019/2oCuatri/TFG/gui_dbjudge/sql_judge/view/qt_view/custom_types/load_custom_types_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadCustomTypesView(object):
    def setupUi(self, LoadCustomTypesView):
        LoadCustomTypesView.setObjectName("LoadCustomTypesView")
        LoadCustomTypesView.resize(640, 480)
        self.gridLayout_3 = QtWidgets.QGridLayout(LoadCustomTypesView)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_file_button = QtWidgets.QPushButton(LoadCustomTypesView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_file_button.sizePolicy().hasHeightForWidth())
        self.load_file_button.setSizePolicy(sizePolicy)
        self.load_file_button.setObjectName("load_file_button")
        self.horizontalLayout.addWidget(self.load_file_button)
        self.label = QtWidgets.QLabel(LoadCustomTypesView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.save_button = QtWidgets.QPushButton(LoadCustomTypesView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.add_row_button = QtWidgets.QPushButton(LoadCustomTypesView)
        self.add_row_button.setObjectName("add_row_button")
        self.horizontalLayout_2.addWidget(self.add_row_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.delete_button = QtWidgets.QPushButton(LoadCustomTypesView)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_2.addWidget(self.delete_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_column_button = QtWidgets.QPushButton(LoadCustomTypesView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_column_button.sizePolicy().hasHeightForWidth())
        self.add_column_button.setSizePolicy(sizePolicy)
        self.add_column_button.setSizeIncrement(QtCore.QSize(0, 0))
        self.add_column_button.setObjectName("add_column_button")
        self.gridLayout_2.addWidget(self.add_column_button, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.table_container = QtWidgets.QGridLayout()
        self.table_container.setObjectName("table_container")
        self.gridLayout_2.addLayout(self.table_container, 0, 1, 2, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 0, 1, 3)
        self.return_button = QtWidgets.QPushButton(LoadCustomTypesView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.return_button.sizePolicy().hasHeightForWidth())
        self.return_button.setSizePolicy(sizePolicy)
        self.return_button.setObjectName("return_button")
        self.gridLayout.addWidget(self.return_button, 4, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(LoadCustomTypesView)
        QtCore.QMetaObject.connectSlotsByName(LoadCustomTypesView)

    def retranslateUi(self, LoadCustomTypesView):
        _translate = QtCore.QCoreApplication.translate
        LoadCustomTypesView.setWindowTitle(_translate("LoadCustomTypesView", "Form"))
        self.load_file_button.setText(_translate("LoadCustomTypesView", "Cargar desde archivo"))
        self.label.setText(_translate("LoadCustomTypesView", "Ningún archivo seleccionado"))
        self.save_button.setText(_translate("LoadCustomTypesView", "Guardar tipos"))
        self.add_row_button.setText(_translate("LoadCustomTypesView", "Añadir fila"))
        self.delete_button.setText(_translate("LoadCustomTypesView", "Eliminar selección"))
        self.add_column_button.setText(_translate("LoadCustomTypesView", "Añadir columna"))
        self.return_button.setText(_translate("LoadCustomTypesView", "Volver al menú"))
