# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/raul/OS/Users/king_/Desktop/carrera/curso2018-2019/2oCuatri/TFG/gui_dbjudge/sql_judge/view/qt_view/modify_scene/modify_scene_menu_questions_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModifySceneMenuQuestions(object):
    def setupUi(self, ModifySceneMenuQuestions):
        ModifySceneMenuQuestions.setObjectName("ModifySceneMenuQuestions")
        ModifySceneMenuQuestions.resize(1017, 592)
        self.gridLayout_3 = QtWidgets.QGridLayout(ModifySceneMenuQuestions)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 2, 1, 2)
        self.question_input = QtWidgets.QPlainTextEdit(ModifySceneMenuQuestions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.question_input.sizePolicy().hasHeightForWidth())
        self.question_input.setSizePolicy(sizePolicy)
        self.question_input.setObjectName("question_input")
        self.gridLayout_2.addWidget(self.question_input, 1, 0, 1, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.add_question_button = QtWidgets.QPushButton(ModifySceneMenuQuestions)
        self.add_question_button.setMaximumSize(QtCore.QSize(120, 30))
        self.add_question_button.setObjectName("add_question_button")
        self.horizontalLayout_6.addWidget(self.add_question_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 2, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 6, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.return_button = QtWidgets.QPushButton(ModifySceneMenuQuestions)
        self.return_button.setMaximumSize(QtCore.QSize(100, 30))
        self.return_button.setObjectName("return_button")
        self.horizontalLayout_2.addWidget(self.return_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 7, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 1, 2)
        self.label = QtWidgets.QLabel(ModifySceneMenuQuestions)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.answer_input = QtWidgets.QPlainTextEdit(ModifySceneMenuQuestions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.answer_input.sizePolicy().hasHeightForWidth())
        self.answer_input.setSizePolicy(sizePolicy)
        self.answer_input.setObjectName("answer_input")
        self.gridLayout_2.addWidget(self.answer_input, 1, 5, 1, 3)
        self.label_4 = QtWidgets.QLabel(ModifySceneMenuQuestions)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 5, 1, 3)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_2.setColumnStretch(2, 2)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout_2.setColumnStretch(5, 2)
        self.gridLayout_2.setColumnStretch(6, 2)
        self.gridLayout_2.setColumnStretch(7, 3)
        self.gridLayout_2.setRowStretch(0, 2)
        self.gridLayout_2.setRowStretch(1, 6)
        self.gridLayout_2.setRowStretch(2, 2)
        self.gridLayout_2.setRowStretch(3, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 4, 0, 1, 4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(ModifySceneMenuQuestions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 985, 175))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_9.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.navbar_config = QtWidgets.QPushButton(ModifySceneMenuQuestions)
        self.navbar_config.setEnabled(True)
        self.navbar_config.setObjectName("navbar_config")
        self.horizontalLayout_4.addWidget(self.navbar_config)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.navbar_gen_data = QtWidgets.QPushButton(ModifySceneMenuQuestions)
        self.navbar_gen_data.setEnabled(True)
        self.navbar_gen_data.setObjectName("navbar_gen_data")
        self.horizontalLayout_4.addWidget(self.navbar_gen_data)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.navbar_questions = QtWidgets.QPushButton(ModifySceneMenuQuestions)
        self.navbar_questions.setEnabled(False)
        self.navbar_questions.setObjectName("navbar_questions")
        self.horizontalLayout_4.addWidget(self.navbar_questions)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_9, 0, 0, 1, 4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(ModifySceneMenuQuestions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(ModifySceneMenuQuestions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.save_questions_button = QtWidgets.QPushButton(ModifySceneMenuQuestions)
        self.save_questions_button.setObjectName("save_questions_button")
        self.horizontalLayout.addWidget(self.save_questions_button)
        spacerItem10 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 2, 4)
        self.gridLayout.setRowStretch(3, 10)
        self.gridLayout.setRowStretch(4, 15)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(ModifySceneMenuQuestions)
        QtCore.QMetaObject.connectSlotsByName(ModifySceneMenuQuestions)

    def retranslateUi(self, ModifySceneMenuQuestions):
        _translate = QtCore.QCoreApplication.translate
        ModifySceneMenuQuestions.setWindowTitle(_translate("ModifySceneMenuQuestions", "Form"))
        self.add_question_button.setText(_translate("ModifySceneMenuQuestions", "Añadir pregunta"))
        self.return_button.setText(_translate("ModifySceneMenuQuestions", "Volver al menú"))
        self.label.setText(_translate("ModifySceneMenuQuestions", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Pregunta</span></p></body></html>"))
        self.label_4.setText(_translate("ModifySceneMenuQuestions", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Consulta correcta</span></p></body></html>"))
        self.navbar_config.setText(_translate("ModifySceneMenuQuestions", "Configuración general"))
        self.navbar_gen_data.setText(_translate("ModifySceneMenuQuestions", "Generar datos"))
        self.navbar_questions.setText(_translate("ModifySceneMenuQuestions", "Configurar preguntas"))
        self.label_2.setText(_translate("ModifySceneMenuQuestions", "Seleccione escenario: "))
        self.save_questions_button.setText(_translate("ModifySceneMenuQuestions", "Guardar preguntas"))
from view.qt_view import resources
